sudo: false
language: python
python:
  - "3.6"
git:
  depth: false

install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install --dev

script:
  - mkdir /tmp
  - pytest --cov

after_success:
  - coveralls

