sudo: false
language: python
python:
  - "3.8"
git:
  depth: false

before_install:
  - pip install poetry~=0.12.17
install:
  - poetry install
  - pip install coveralls
  - pipenv install --dev
script:
  - pytest --cov
after_success:
  - coveralls

