sudo: false
language: python
python:
  - "3.8"
git:
  depth: false

install:
  - poetry install --dev
  - pip install coveralls
  - pipenv install --dev

script:
  - pytest --cov

after_success:
  - coveralls

