sudo: false
language: python
python:
  - "3.8"
git:
  depth: false

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
install:
  - poetry install
  - pip install coveralls
  - pipenv install --dev
script:
  - pytest --cov
after_success:
  - coveralls

